import { StyleSheet, Platform } from 'react-native';
import {
  taskAgeColumnWidth,
  taskArchiveColumnMarginLeft,
  taskArchiveColumnWidth,
  taskCheckboxColumnWidth,
  taskDueColumnMarginLeft,
  taskDueColumnWidth,
  taskHandleColumnWidth,
  taskPriorityColumnMarginLeft,
  taskPriorityColumnWidth,
  taskProjectSlotWidth,
  taskRowPaddingRight,
  taskStatusColumnMarginLeft,
  taskStatusColumnWidth,
  taskStatusSlotGap,
  taskStatusSlotWidth,
} from '../../components/todoColumns';
import {
  priorityPopoverWidth,
  defaultVisibleTaskRows,
  todoRowHeight,
  incomingRowHeight,
  taskHeaderHeight,
  taskBoxMaxHeight,
  incomingBoxMaxHeight,
  workspaceContentMaxWidth,
  workspaceInboxColumnWidth,
  workspacePaneGap,
  workspaceBoardPadding,
} from './constants';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#fff',
  },
  list: {
    flex: 1,
  },
  todoBoard: {
    flex: 1,
    width: '100%',
    maxWidth: workspaceContentMaxWidth,
    alignSelf: 'center',
    padding: 12,
    gap: 12,
  },
  todoBoardWithAssigned: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    minHeight: 0,
  },
  todoListPane: {
    flex: 1,
    minWidth: 0,
    gap: 12,
  },
  activeTasksBox: {
    maxHeight: taskBoxMaxHeight,
    flexShrink: 0,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  activeTasksList: {
    maxHeight: todoRowHeight * defaultVisibleTaskRows,
    flexGrow: 0,
  },
  completedDivider: {
    height: 2,
    backgroundColor: '#e5e7eb',
  },
  completedBox: {
    flex: 1,
    minHeight: todoRowHeight * 3,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fafafa',
    overflow: 'hidden',
  },
  completedBoxHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    height: taskHeaderHeight,
    paddingHorizontal: 8,
    gap: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#d1d5db',
    backgroundColor: '#f3f4f6',
  },
  completedPaneTab: {
    height: 20,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
  },
  completedPaneTabActive: {
    backgroundColor: '#fff',
  },
  completedPaneTabText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9ca3af',
    letterSpacing: 0.3,
  },
  completedPaneTabTextActive: {
    color: '#6b7280',
  },
  completedPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#166534',
    letterSpacing: 0.3,
  },
  completedBoxScroll: {
    flex: 1,
    minHeight: 0,
  },
  completedPaneEmpty: {
    color: '#9ca3af',
    fontSize: 13,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  assignedToMePanel: {
    width: workspaceInboxColumnWidth,
    maxWidth: '36%',
    maxHeight: incomingBoxMaxHeight,
    flexShrink: 0,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  assignedToMePanelTitle: {
    height: taskHeaderHeight,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#d1d5db',
    backgroundColor: '#f3f4f6',
    color: '#9ca3af',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.3,
    lineHeight: taskHeaderHeight - 1,
  },
  assignedToMePanelList: {
    maxHeight: incomingRowHeight * defaultVisibleTaskRows,
    flexGrow: 0,
  },
  assignedToMeInlinePanel: {
    maxHeight: incomingBoxMaxHeight,
    flexShrink: 0,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  assignedToMeEmpty: {
    minHeight: 34,
    paddingHorizontal: 16,
    paddingVertical: 8,
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
  },
  inboxView: {
    flex: 1,
  },
  inboxViewContent: {
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 36,
  },
  inboxViewPanel: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  inboxViewEmpty: {
    color: '#9ca3af',
    fontSize: 13,
    fontWeight: '600',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  inboxSectionHeader: {
    minHeight: 24,
    paddingHorizontal: 16,
    paddingVertical: 5,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  inboxSectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#6b7280',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  notesPanelScroll: {
    maxHeight: incomingBoxMaxHeight - taskHeaderHeight,
  },
  notesPanelContent: {
    padding: 10,
    gap: 10,
  },
  notesPanelContentFull: {
    padding: 14,
    gap: 14,
  },
  notesFieldGroup: {
    gap: 5,
  },
  notesFieldLabel: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  notesWorkspace: {
    width: '100%',
  },
  notesMindmapPane: {
    flex: 1,
    gap: 10,
    minWidth: 0,
  },
  notesMindmapHeader: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  notesMindmapHeading: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  notesAutosaveText: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
  },
  notesCreateButton: {
    minHeight: 24,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: '#6366f1',
    borderRadius: 6,
  },
  notesCreateButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  notesTemplatePicker: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    padding: 10,
    gap: 8,
  },
  notesTemplatePickerTitle: {
    color: '#374151',
    fontSize: 12,
    fontWeight: '700',
  },
  notesTemplateGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  notesTemplateCard: {
    width: 220,
    minHeight: 144,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    borderRadius: 8,
    overflow: 'hidden',
  },
  notesTemplateCardPressed: {
    borderColor: '#6366f1',
    backgroundColor: '#eef2ff',
  },
  notesTemplateName: {
    paddingHorizontal: 9,
    paddingTop: 6,
    paddingBottom: 8,
    color: '#374151',
    fontSize: 12,
    fontWeight: '700',
  },
  notesMindmapTabs: {
    minHeight: 34,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
  },
  notesMindmapEmpty: {
    paddingVertical: 10,
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
  },
  notesMindmapTab: {
    maxWidth: 210,
    minHeight: 30,
    paddingHorizontal: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#f9fafb',
    borderRadius: 7,
  },
  notesMindmapTabActive: {
    borderColor: '#4f46e5',
    backgroundColor: '#eef2ff',
  },
  notesMindmapTabPressed: {
    borderColor: '#818cf8',
    backgroundColor: '#f1f5ff',
  },
  notesMindmapTabText: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
  },
  notesMindmapTabTextActive: {
    color: '#3730a3',
  },
  notesMindmapCard: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    borderRadius: 8,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 7,
  },
  notesMindmapCardHeader: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  notesMindmapTitleGroup: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  notesMindmapTitle: {
    color: '#374151',
    fontSize: 14,
    fontWeight: '700',
  },
  notesMindmapMeta: {
    color: '#9ca3af',
    fontSize: 11,
    fontWeight: '600',
  },
  notesMindmapCardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  notesMindmapHeaderAction: {
    minHeight: 24,
    paddingHorizontal: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#dbe4f0',
    backgroundColor: '#f8fafc',
    borderRadius: 6,
  },
  notesMindmapHeaderActionText: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '700',
  },
  notesMindmapDangerAction: {
    borderColor: '#fecdd3',
    backgroundColor: '#fff1f2',
  },
  notesMindmapDangerActionText: {
    color: '#be123c',
  },
  notesMindmapInspector: {
    minHeight: 34,
    paddingHorizontal: 8,
    paddingVertical: 7,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f8fafc',
    borderRadius: 7,
  },
  notesMindmapInspectorGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minWidth: 0,
  },
  notesMindmapInspectorLabel: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.2,
    textTransform: 'uppercase',
  },
  notesMindmapSegmentedControl: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#dbe4f0',
    backgroundColor: '#fff',
    borderRadius: 6,
    overflow: 'hidden',
  },
  notesMindmapSegment: {
    minHeight: 24,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notesMindmapSegmentActive: {
    backgroundColor: '#eef2ff',
  },
  notesMindmapSegmentText: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '700',
  },
  notesMindmapSegmentTextActive: {
    color: '#3730a3',
  },
  notesMindmapInspectorToggles: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  notesMindmapAddTopic: {
    minHeight: 26,
    paddingHorizontal: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderRadius: 6,
    backgroundColor: '#4f46e5',
  },
  notesMindmapAddTopicText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  notesMindmapToggle: {
    minHeight: 24,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    borderColor: '#dbe4f0',
    backgroundColor: '#fff',
    borderRadius: 6,
  },
  notesMindmapToggleActive: {
    borderColor: '#a5b4fc',
    backgroundColor: '#eef2ff',
  },
  notesMindmapToggleDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#cbd5e1',
  },
  notesMindmapToggleDotActive: {
    backgroundColor: '#4f46e5',
  },
  notesMindmapToggleText: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '700',
  },
  notesMindmapToggleTextActive: {
    color: '#3730a3',
  },
  notesMindmapCanvas: {
    position: 'relative',
    height: 560,
    borderWidth: 1,
    borderColor: '#dbe4f0',
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    overflow: 'hidden',
  },
  notesMindmapCanvasCompact: {
    height: 380,
  },
  notesMindmapCanvasConnectors: {
    position: 'absolute',
    inset: 0,
  },
  notesMindmapNode: {
    position: 'absolute',
    minHeight: 38,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#fff',
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 12,
    paddingRight: 12,
    shadowColor: '#0f172a',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  notesMindmapNodeSelected: {
    borderColor: '#4f46e5',
    shadowOpacity: 0.22,
    shadowRadius: 12,
  },
  notesMindmapNodeDropTarget: {
    borderColor: '#4f46e5',
    borderWidth: 3,
    backgroundColor: '#e0e7ff',
    shadowOpacity: 0.3,
    shadowRadius: 14,
  },
  notesMindmapRootNode: {
    minHeight: 42,
    borderColor: '#4f46e5',
    backgroundColor: '#eef2ff',
    paddingHorizontal: 16,
    shadowOpacity: 0.16,
    shadowRadius: 12,
  },
  notesMindmapChildNode: {
    minHeight: 32,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
  },
  notesMindmapNodeInput: {
    flex: 1,
    minWidth: 0,
    color: '#374151',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    padding: 0,
    outlineStyle: 'none' as never,
  },
  notesMindmapRootInput: {
    color: '#3730a3',
    fontSize: 14,
    fontWeight: '800',
  },
  notesMindmapChildNodeInput: {
    fontSize: 11,
    fontWeight: '600',
  },
  notesMindmapTopicInput: {
    color: '#0f172a',
  },
  notesMindmapNodeActionGroup: {
    position: 'absolute',
    right: 8,
    bottom: '100%',
    marginBottom: 4,
    zIndex: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    padding: 2,
    borderRadius: 11,
    backgroundColor: 'rgba(255, 255, 255, 0.94)',
    borderWidth: 1,
    borderColor: '#dbe4f0',
    shadowColor: '#0f172a',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  notesMindmapNodeActionGroupBelow: {
    bottom: undefined,
    marginBottom: 0,
    top: '100%',
    marginTop: 4,
  },
  notesMindmapRootActionGroup: {
    right: 0,
  },
  notesMindmapRootAddAction: {
    minHeight: 24,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#4f46e5',
  },
  notesMindmapRootAddActionText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  notesMindmapNodeAction: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: '#f8fafc',
  },
  notesMindmapNodeActionText: {
    color: '#64748b',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 15,
  },
  notesMindmapCanvasAddNode: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: '#4f46e5',
    shadowColor: '#312e81',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  notesMindmapCanvasAddNodeText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 24,
  },
  authScroll: {
    flexGrow: 1,
  },
  authPanel: {
    flex: 1,
    width: '100%',
    maxWidth: 360,
    alignSelf: 'center',
    paddingHorizontal: 28,
    paddingTop: 56,
    paddingBottom: 24,
  },
  authBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
    gap: 10,
  },
  authLogo: {
    width: 36,
    height: 36,
    borderRadius: 9,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authLogoImage: {
    width: 36,
    height: 36,
  },
  authBrandName: {
    fontSize: 22,
    fontWeight: '700',
    color: '#111827',
  },
  authTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
    marginBottom: 4,
  },
  authTitleSub: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
    marginBottom: 28,
  },
  authLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 6,
    marginTop: 0,
  },
  authPasswordHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
    marginTop: 14,
  },
  authSuccessBox: {
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#86efac',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 14,
    marginBottom: 12,
  },
  authSuccessText: {
    color: '#16a34a',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  socialGridBtnSoon: {
    opacity: 0.5,
  },
  socialComingSoon: {
    fontSize: 11,
    color: '#9ca3af',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  authLinksRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  authLink: {
    color: '#6366f1',
    fontSize: 13,
  },
  authSubtitleText: {
    color: '#6b7280',
    fontSize: 15,
  },
  authSubtitleLink: {
    color: '#6366f1',
    fontSize: 15,
    fontWeight: '600',
  },
  socialGrid: {
    flexDirection: 'column',
    gap: 10,
  },
  socialGridBtn: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 48,
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    backgroundColor: '#fff',
    gap: 8,
  },
  socialGridBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111827',
  },
  googleG: {
    fontSize: 22,
    fontWeight: '700',
    color: '#4285F4',
    lineHeight: 24,
  },
  appleIcon: {
    fontSize: 18,
    color: '#111827',
    lineHeight: 22,
  },
  githubIcon: {
    fontSize: 11,
    fontWeight: '800',
    color: '#111827',
    letterSpacing: -0.5,
  },
  ssoIcon: {
    fontSize: 15,
    color: '#6b7280',
  },
  socialBtnText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
  },
  authDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 28,
  },
  authDividerLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#d1d5db',
  },
  authDividerText: {
    color: '#6b7280',
    fontSize: 13,
    paddingHorizontal: 12,
  },
  authMessage: {
    color: '#6b7280',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 10,
  },
  authConfirmMessage: {
    color: '#16a34a',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    paddingVertical: 14,
  },
  authInput: {
    height: 48,
    backgroundColor: '#eef2ff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#c7d2fe',
    paddingHorizontal: 16,
    fontSize: 14,
    color: '#111827',
    marginBottom: 16,
  },
  authEmailInput: {
    marginBottom: 12,
  },
  authInputError: {
    borderColor: '#ef4444',
    borderWidth: 1.5,
  },
  authFieldError: {
    color: '#ef4444',
    fontSize: 13,
    marginBottom: 0,
  },
  authPasswordWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
    backgroundColor: '#eef2ff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#c7d2fe',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  authPasswordInput: {
    flex: 1,
    height: '100%',
    fontSize: 14,
    color: '#111827',
  },
  passwordToggleText: {
    fontSize: 13,
    color: '#9ca3af',
    paddingLeft: 8,
  },
  authSubmitBtn: {
    height: 48,
    backgroundColor: '#6366f1',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 0,
  },
  authSubmitBtnMuted: {
    backgroundColor: '#9ca3af',
  },
  authSubmitBtnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  forgotBtn: {
    alignItems: 'flex-end',
    marginTop: 12,
  },
  forgotBtnText: {
    color: '#6366f1',
    fontSize: 13,
    fontWeight: '600',
  },
  authFooter: {
    paddingBottom: 36,
    alignItems: 'center',
  },
  authFooterText: {
    color: '#9ca3af',
    fontSize: 13,
  },
  accountMenuButton: {
    flexDirection: 'row',
    alignItems: 'center',
    maxWidth: 260,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  accountMenuButtonText: {
    color: '#6b7280',
    fontSize: 13,
    fontWeight: '600',
    maxWidth: 220,
  },
  accountMenuCaret: {
    color: '#6366f1',
    fontSize: 11,
    fontWeight: '700',
    marginLeft: 6,
  },
  accountMenuBackdrop: {
    flex: 1,
    alignItems: 'flex-end',
    backgroundColor: 'rgba(17, 24, 39, 0.12)',
    paddingTop: 64,
    paddingRight: 16,
  },
  accountMenuCard: {
    width: 240,
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  accountMenuName: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '700',
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 2,
  },
  accountMenuEmail: {
    color: '#6b7280',
    fontSize: 11,
    paddingHorizontal: 12,
    paddingTop: 2,
    paddingBottom: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e5e7eb',
  },
  accountMenuItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  accountMenuItemText: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '600',
  },
  accountMenuItemTextActive: {
    color: '#4338ca',
  },
  accountMenuMutedText: {
    color: '#9ca3af',
    fontSize: 13,
    fontWeight: '600',
  },
  accountMenuSection: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#e5e7eb',
    paddingTop: 6,
    marginTop: 4,
  },
  accountMenuSectionHeader: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  accountMenuSectionTitle: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  accountMenuSectionAction: {
    color: '#6366f1',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 20,
  },
  accountMenuSignOutText: {
    color: '#6366f1',
    fontSize: 13,
    fontWeight: '700',
  },
  teamPanel: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    width: '100%',
    maxWidth: workspaceContentMaxWidth,
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingTop: 2,
    paddingBottom: 0,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'transparent',
  },
  workspaceLabel: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  workspaceTabs: {
    alignItems: 'center',
    paddingBottom: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#d1d5db',
    backgroundColor: '#fff',
  },
  workspaceTab: {
    height: 30,
    maxWidth: 180,
    backgroundColor: 'transparent',
    paddingHorizontal: 6,
    paddingVertical: 2,
    justifyContent: 'center',
    position: 'relative',
    zIndex: 1,
  },
  workspaceTabFirst: {},
  workspaceTabJoined: {},
  workspaceTabLast: {},
  workspaceTabActive: {
    backgroundColor: '#eef2ff',
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderLeftColor: '#6366f1',
    borderBottomColor: 'transparent',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    marginLeft: -1,
    marginBottom: -1,
    zIndex: 2,
  },
  workspaceTabDivider: {
    position: 'absolute',
    right: 0,
    top: 6,
    width: 1,
    height: 18,
    backgroundColor: '#d1d5db',
  },
  workspaceTabText: {
    color: '#374151',
    fontWeight: '600',
    fontSize: 13,
  },
  workspaceTabTextActive: {
    color: '#4338ca',
  },
  workspaceAddTab: {
    width: 30,
    height: 30,
    borderColor: '#d1d5db',
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  workspaceAddText: {
    color: '#6366f1',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 22,
  },
  workspaceTabsScroll: {
    flex: 1,
  },
  teamsBtn: {
    flexShrink: 0,
    height: 30,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  teamsBtnActive: {
    backgroundColor: '#eef2ff',
    borderColor: '#6366f1',
  },
  teamsBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
  },
  teamsBtnTextActive: {
    color: '#4338ca',
  },
  teamsGrid: {
    flex: 1,
  },
  teamsGridContent: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 16,
    gap: 12,
  },
  organizationsView: {
    flex: 1,
    backgroundColor: '#fff',
  },
  organizationsViewContent: {
    padding: 16,
    gap: 12,
  },
  organizationSection: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#fff',
    padding: 12,
  },
  organizationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  organizationTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  organizationTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
  },
  organizationMeta: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9ca3af',
    marginTop: 2,
  },
  organizationAddTeamButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    flexShrink: 0,
  },
  organizationAddTeamText: {
    color: '#6366f1',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 24,
  },
  organizationTeamTabs: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingRight: 2,
  },
  organizationTeamTab: {
    minHeight: 36,
    maxWidth: 190,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  organizationTeamTabActive: {
    backgroundColor: '#eef2ff',
    borderColor: '#6366f1',
  },
  organizationTeamTabText: {
    color: '#374151',
    fontSize: 13,
    fontWeight: '700',
    minWidth: 0,
  },
  organizationTeamTabTextActive: {
    color: '#4338ca',
  },
  organizationTeamMeta: {
    color: '#9ca3af',
    fontSize: 11,
    fontWeight: '700',
  },
  organizationEmptyTeamTab: {
    minHeight: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#d1d5db',
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  organizationEmptyTeamText: {
    color: '#9ca3af',
    fontSize: 13,
    fontWeight: '600',
  },
  organizationCardNew: {
    minHeight: 72,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  organizationCardNewIcon: {
    fontSize: 22,
    color: '#6366f1',
    fontWeight: '300',
    lineHeight: 26,
  },
  organizationCardNewText: {
    color: '#6366f1',
    fontSize: 13,
    fontWeight: '700',
  },
  projectsGrid: {
    flex: 1,
  },
  projectsGridContent: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 16,
    gap: 12,
  },
  projectCard: {
    width: 220,
    minHeight: 108,
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    justifyContent: 'center',
  },
  searchResultDimmed: {
    opacity: 0.36,
  },
  projectCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  projectCardAvatar: {
    width: 28,
    height: 28,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  projectCardAvatarText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
  },
  projectCardName: {
    flex: 1,
    minWidth: 0,
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
  },
  projectCardMeta: {
    fontSize: 12,
    color: '#6b7280',
    fontWeight: '600',
  },
  projectCardNew: {
    width: 220,
    minHeight: 108,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  projectCardNewIcon: {
    fontSize: 24,
    color: '#6366f1',
    fontWeight: '300',
    lineHeight: 30,
  },
  projectCardNewText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#6366f1',
  },
  calendarView: {
    flex: 1,
    backgroundColor: '#fff',
  },
  calendarViewContent: {
    padding: 16,
  },
  calendarViewPanel: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    borderRadius: 8,
    overflow: 'hidden',
  },
  calendarViewHeader: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  calendarViewEyebrow: {
    color: '#9ca3af',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  calendarViewTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 2,
  },
  calendarViewActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  calendarViewNavButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  calendarViewNavText: {
    color: '#374151',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 20,
  },
  calendarViewTodayButton: {
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    backgroundColor: '#fff',
  },
  calendarViewTodayText: {
    color: '#374151',
    fontSize: 13,
    fontWeight: '700',
  },
  calendarViewModeBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#fff',
  },
  calendarViewModeButton: {
    minHeight: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    paddingHorizontal: 12,
    paddingVertical: 6,
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  calendarViewModeButtonActive: {
    borderColor: '#111827',
    backgroundColor: '#111827',
  },
  calendarViewModeButtonText: {
    color: '#374151',
    fontSize: 13,
    fontWeight: '700',
  },
  calendarViewModeButtonTextActive: {
    color: '#fff',
  },
  calendarViewWeekdays: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  calendarViewWeekday: {
    width: '14.2857%',
    paddingVertical: 8,
    textAlign: 'center',
    color: '#9ca3af',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  calendarViewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarViewDayCell: {
    width: '14.2857%',
    minHeight: 116,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#e5e7eb',
    padding: 8,
    backgroundColor: '#fff',
  },
  calendarViewDayBlank: {
    backgroundColor: '#f9fafb',
  },
  calendarViewDayToday: {
    backgroundColor: '#eef2ff',
  },
  calendarViewDaySelected: {
    borderColor: '#6366f1',
    borderWidth: 1,
  },
  calendarViewDayNumber: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 8,
  },
  calendarViewDayNumberToday: {
    color: '#4338ca',
  },
  calendarViewItems: {
    gap: 5,
  },
  calendarViewTask: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 6,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 6,
  },
  calendarViewPriorityDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    flexShrink: 0,
  },
  calendarViewTaskText: {
    flex: 1,
    minWidth: 0,
    color: '#111827',
    fontSize: 12,
    fontWeight: '700',
  },
  calendarViewTaskDoneText: {
    color: '#9ca3af',
    textDecorationLine: 'line-through',
  },
  calendarViewMoreText: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '700',
  },
  calendarDayView: {
    flexDirection: 'row',
    minHeight: 520,
  },
  calendarDayViewStacked: {
    flexDirection: 'column',
  },
  calendarDayAgenda: {
    flex: 1,
    borderRightWidth: 1,
    borderRightColor: '#e5e7eb',
    minWidth: 0,
  },
  calendarDayAgendaHeader: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  calendarDayAgendaTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
  },
  calendarDayAgendaDate: {
    color: '#9ca3af',
    fontSize: 13,
    fontWeight: '700',
  },
  calendarViewEmpty: {
    color: '#9ca3af',
    fontSize: 15,
    fontWeight: '600',
    padding: 16,
  },
  calendarDayTask: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  calendarDayTaskBody: {
    flex: 1,
    minWidth: 0,
  },
  calendarDayTaskTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
  },
  calendarDayTaskNote: {
    color: '#6b7280',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 2,
  },
  calendarDayNotes: {
    width: 340,
    padding: 14,
    backgroundColor: '#fff',
  },
  calendarDayNotesStacked: {
    width: '100%',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  calendarDayNotesTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 8,
  },
  calendarDayNotesInput: {
    minHeight: 420,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    padding: 12,
    color: '#111827',
    fontSize: 15,
    fontWeight: '500',
    backgroundColor: '#f9fafb',
  },
  calendarWeekHeaderDay: {
    width: '14.2857%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    gap: 2,
  },
  calendarWeekHeaderDaySelected: {
    backgroundColor: '#eef2ff',
  },
  calendarWeekHeaderText: {
    color: '#9ca3af',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  calendarWeekHeaderNumber: {
    color: '#374151',
    fontSize: 15,
    fontWeight: '800',
  },
  calendarWeekHeaderTextSelected: {
    color: '#4338ca',
  },
  calendarWeekGrid: {
    flexDirection: 'row',
    minHeight: 520,
  },
  calendarWeekDayColumn: {
    width: '14.2857%',
    borderRightWidth: 1,
    borderRightColor: '#e5e7eb',
    padding: 8,
    gap: 6,
  },
  calendarWeekEmpty: {
    color: '#d1d5db',
    fontSize: 11,
    fontWeight: '700',
  },
  teamCard: {
    width: 200,
    borderRadius: 14,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    overflow: 'hidden',
  },
  teamCardBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 72,
    borderRadius: 14,
  },
  teamCardAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 36,
    marginBottom: 8,
  },
  teamCardAvatarText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  teamCardName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 2,
  },
  teamCardMeta: {
    fontSize: 11,
    color: '#6b7280',
  },
  teamCardAddBtn: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#f3f4f6',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  teamCardAddBtnText: {
    fontSize: 18,
    color: '#6b7280',
    lineHeight: 22,
    fontWeight: '300',
  },
  teamCardNew: {
    width: 200,
    height: 130,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  teamCardNewIcon: {
    fontSize: 22,
    color: '#d1d5db',
    fontWeight: '300',
    lineHeight: 28,
  },
  teamCardNewText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#9ca3af',
  },
  memberPanel: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e5e7eb',
  },
  panelTitle: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 8,
  },
  memberList: {
    marginBottom: 8,
  },
  memberChip: {
    color: '#374151',
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 8,
    fontSize: 11,
  },
  compactForm: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  compactInput: {
    flex: 1,
    height: 40,
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 13,
    color: '#111827',
    marginRight: 8,
  },
  smallBtn: {
    height: 40,
    backgroundColor: '#6366f1',
    borderRadius: 8,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 13,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    maxWidth: workspaceContentMaxWidth,
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 0,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'transparent',
    backgroundColor: '#fff',
  },
  inputBarWithInboxSidePanel: {
    paddingRight: workspaceBoardPadding + workspacePaneGap + workspaceInboxColumnWidth,
  },
  todoInputWrap: {
    flex: 1,
    marginRight: 10,
  },
  input: {
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#111827',
  },
  assigneePill: {
    borderColor: '#d1d5db',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 8,
  },
  assigneePillActive: {
    backgroundColor: '#eef2ff',
    borderColor: '#6366f1',
  },
  assigneePillText: {
    color: '#374151',
    fontSize: 11,
    fontWeight: '600',
  },
  assigneePillTextActive: {
    color: '#4338ca',
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 14,
    height: 36,
    justifyContent: 'center',
    minWidth: 86,
  },
  addBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 15,
  },
  addBtnPressed: {
    opacity: 0.88,
    transform: [{ translateY: 1 }],
  },
  btnPressed: {
    opacity: 0.8,
  },
  empty: {
    textAlign: 'center',
    color: '#9ca3af',
    marginTop: 80,
    fontSize: 15,
  },
  error: {
    color: '#b91c1c',
    backgroundColor: '#fee2e2',
    margin: 16,
    padding: 12,
    borderRadius: 8,
    fontSize: 13,
  },
  message: {
    color: '#166534',
    backgroundColor: '#dcfce7',
    margin: 16,
    padding: 12,
    borderRadius: 8,
    fontSize: 13,
  },
  toast: {
    position: 'absolute',
    bottom: 24,
    alignSelf: 'center',
    backgroundColor: '#111827',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  toastText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
  },
  toastRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  toastActionText: {
    color: '#a5b4fc',
    fontSize: 13,
    fontWeight: '800',
  },
  sectionDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 4,
    gap: 10,
  },
  sectionDividerLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#d1d5db',
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9ca3af',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  popoverBackdrop: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  priorityPopover: {
    position: 'absolute',
    width: priorityPopoverWidth,
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 10,
  },
  priorityPopoverOption: {
    height: 24,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    gap: 8,
  },
  priorityPopoverOptionActive: {
    backgroundColor: '#f3f4f6',
  },
  priorityPopoverSwatch: {
    width: 14,
    height: 14,
    borderRadius: 4,
  },
  priorityPopoverLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
  },
  priorityPopoverLabelActive: {
    color: '#111827',
  },
  priorityPopoverCheck: {
    fontSize: 13,
    fontWeight: '700',
    color: '#6366f1',
  },
  calendarCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    width: 320,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  editTodoCard: {
    width: 380,
    maxWidth: '92%',
    padding: 16,
  },
  editTodoHeader: {
    marginBottom: 10,
  },
  editTodoScroll: {
    flexGrow: 0,
  },
  editTodoScrollContent: {
    paddingBottom: 4,
    gap: 10,
  },
  editTodoFieldGroup: {
    gap: 8,
  },
  editTodoSection: {
    gap: 8,
  },
  editTodoSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 16,
  },
  editTodoSectionLabel: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  editTodoCalendarPanel: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 6,
    backgroundColor: '#f9fafb',
  },
  clearDateInlineButton: {
    paddingVertical: 0,
    paddingLeft: 12,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 30,
    marginBottom: 0,
  },
  calendarNavBtn: {
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  calendarNavText: {
    fontSize: 22,
    color: '#6366f1',
    fontWeight: '600',
    lineHeight: 24,
  },
  calendarTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
  },
  weekdayRow: {
    flexDirection: 'row',
    marginBottom: 2,
  },
  weekdayText: {
    width: '14.2857%',
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '600',
    color: '#9ca3af',
    paddingVertical: 2,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarDay: {
    width: '14.2857%',
    height: 24,
    minHeight: 24,
    maxHeight: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  calendarDayBlank: {
    opacity: 0,
  },
  calendarDayToday: {
    borderWidth: 1.5,
    borderColor: '#6366f1',
  },
  calendarDaySelected: {
    backgroundColor: '#6366f1',
  },
  calendarDayText: {
    fontSize: 13,
    color: '#374151',
  },
  calendarDayTodayText: {
    color: '#6366f1',
    fontWeight: '700',
  },
  calendarDaySelectedText: {
    color: '#fff',
    fontWeight: '700',
  },
  calendarActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#e5e7eb',
    paddingTop: 12,
  },
  calendarActionText: {
    color: '#6366f1',
    fontWeight: '600',
    fontSize: 13,
  },
  calendarCancelText: {
    color: '#9ca3af',
    fontWeight: '600',
    fontSize: 13,
  },
  editModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 0,
  },
  editModalInput: {
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    height: 40,
    paddingHorizontal: 12,
    paddingVertical: 0,
    fontSize: 14,
    color: '#111827',
    marginBottom: 0,
  },
  editTodoTaskInput: {
    fontSize: 15,
    fontWeight: '600',
  },
  editModalNoteInput: {
    height: 48,
    minHeight: 48,
    paddingVertical: 0,
    marginBottom: 0,
    textAlignVertical: 'top',
  },
  editModalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  editTodoFooter: {
    marginTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#e5e7eb',
    paddingTop: 10,
  },
  editModalPillRow: {
    marginBottom: 0,
  },
  sortBar: {
    flexDirection: 'row',
    alignItems: 'center',
    height: taskHeaderHeight,
    paddingRight: taskRowPaddingRight,
    borderBottomWidth: 1,
    borderBottomColor: '#d1d5db',
    backgroundColor: '#f3f4f6',
  },
  sortHandleSpacer: {
    width: taskHandleColumnWidth,
    flexShrink: 0,
  },
  sortCheckboxSpacer: {
    width: taskCheckboxColumnWidth,
    flexShrink: 0,
  },
  sortColInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  sortTextHeaderHovered: {
    backgroundColor: '#eef2ff',
    borderRadius: 5,
  },
  sortIconHeader: {
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
  },
  sortIconHeaderHovered: {
    backgroundColor: '#eef2ff',
  },
  sortIconHeaderActive: {
    backgroundColor: '#e0e7ff',
  },
  projectFilterPicker: {
    width: 260,
    maxHeight: '70%',
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 8,
  },
  projectFilterTitle: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
  },
  projectFilterOption: {
    minHeight: 40,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 5,
  },
  projectFilterOptionActive: {
    backgroundColor: '#eef2ff',
  },
  projectFilterOptionLabel: {
    flex: 1,
    color: '#374151',
    fontSize: 14,
  },
  projectFilterOptionLabelActive: {
    color: '#312e81',
    fontWeight: '700',
  },
  projectFilterCheck: {
    color: '#4338ca',
    fontSize: 16,
    fontWeight: '700',
  },
  sortColTask: {
    flex: 1,
    height: 20,
  },
  sortPriorityGroup: {
    width: taskPriorityColumnWidth,
    marginLeft: taskPriorityColumnMarginLeft,
    flexShrink: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  sortColPriority: {
    width: 20,
    flexShrink: 0,
  },
  sortColAssignedBy: {
    width: 20,
    flexShrink: 0,
  },
  sortStatusGap: {
    width: taskStatusColumnWidth,
    marginLeft: taskStatusColumnMarginLeft,
    flexShrink: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: taskStatusSlotGap,
  },
  sortColProject: {
    width: taskProjectSlotWidth,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  sortColStatus: {
    width: taskStatusSlotWidth,
    flexShrink: 0,
  },
  prioritySortSquare: {
    width: 10,
    height: 10,
    borderRadius: 2,
  },
  sortColDue: {
    width: taskDueColumnWidth,
    marginLeft: taskDueColumnMarginLeft,
    height: 20,
  },
  sortColAgeGap: {
    width: taskAgeColumnWidth,
    marginLeft: 0,
    flexShrink: 0,
  },
  sortArchiveGap: {
    width: taskArchiveColumnWidth,
    marginLeft: taskArchiveColumnMarginLeft,
    flexShrink: 0,
  },
  sortColAdded: {
    width: 56,
    marginLeft: 8,
  },
  sortColLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9ca3af',
    letterSpacing: 0.3,
  },
  sortColIndicator: {
    fontSize: 11,
    color: '#c4c9d4',
  },
  sortColLabelActive: {
    color: '#4338ca',
  },
  titleBar: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
    maxWidth: workspaceContentMaxWidth,
    alignSelf: 'center',
    paddingHorizontal: 14,
    paddingTop: Platform.OS === 'ios' ? 52 : 12,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'transparent',
    backgroundColor: '#fff',
    gap: 10,
  },
  titleBarLeft: {
    flexDirection: 'column',
    flex: 1,
    maxWidth: 340,
  },
  userIdentityRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  userNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 2,
    marginTop: 6,
    marginLeft: 48,
  },
  userNavLink: {
    paddingVertical: 1,
    paddingHorizontal: 2,
  },
  userNavLinkText: {
    fontSize: 11,
    color: '#6b7280',
  },
  userNavDot: {
    fontSize: 11,
    color: '#d1d5db',
  },
  userNavSignOutText: {
    fontSize: 11,
    color: '#ef4444',
  },
  userNavStatusEdit: {
    marginTop: 4,
    marginLeft: 48,
    paddingVertical: 1,
    paddingHorizontal: 2,
  },
  userNavStatusInput: {
    marginTop: 4,
    marginLeft: 48,
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    width: 200,
  },
  userNavSections: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 6,
    marginLeft: 48,
  },
  userNavSection: {
    flexDirection: 'column',
    minWidth: 80,
  },
  userNavSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 2,
  },
  userNavSectionTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9ca3af',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  userNavSectionAction: {
    fontSize: 13,
    color: '#9ca3af',
    fontWeight: '700',
    lineHeight: 14,
  },
  userNavSectionItem: {
    paddingVertical: 1,
  },
  userNavSectionItemText: {
    fontSize: 11,
    color: '#374151',
  },
  userNavSectionItemTextActive: {
    color: '#6366f1',
    fontWeight: '600',
  },
  userNavSectionMuted: {
    fontSize: 11,
    color: '#d1d5db',
  },
  navDropdownBackdrop: {
    flex: 1,
  },
  navDropdownCard: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 112 : 72,
    left: 14,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e5e7eb',
    paddingVertical: 8,
    minWidth: 240,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
  navDropdownName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#111827',
    paddingHorizontal: 14,
    paddingTop: 4,
    paddingBottom: 1,
  },
  navDropdownEmail: {
    fontSize: 11,
    color: '#9ca3af',
    paddingHorizontal: 14,
    paddingBottom: 8,
  },
  navDropdownStatusPressable: {
    marginHorizontal: 10,
    marginBottom: 8,
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  navDropdownStatusText: {
    fontSize: 11,
    color: '#6b7280',
    fontStyle: 'italic',
  },
  navDropdownStatusPlaceholder: {
    fontSize: 11,
    color: '#d1d5db',
    fontStyle: 'italic',
  },
  navDropdownStatusInput: {
    fontSize: 11,
    color: '#6b7280',
    fontStyle: 'italic',
    marginHorizontal: 10,
    marginBottom: 8,
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#6366f1',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  navDropdownDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#e5e7eb',
    marginVertical: 4,
  },
  navDropdownSection: {
    paddingBottom: 2,
  },
  navDropdownSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 2,
  },
  navDropdownSectionTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9ca3af',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  navDropdownSectionAction: {
    fontSize: 13,
    color: '#6b7280',
    fontWeight: '700',
  },
  navDropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  navDropdownItemText: {
    fontSize: 13,
    color: '#111827',
  },
  navDropdownItemTextActive: {
    color: '#6366f1',
    fontWeight: '600',
  },
  navDropdownMutedText: {
    fontSize: 13,
    color: '#9ca3af',
  },
  navDropdownSettingsHeader: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9ca3af',
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 4,
  },
  navDropdownThemeItem: {
    minHeight: 34,
    paddingLeft: 20,
    paddingRight: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  navDropdownThemeCheck: {
    fontSize: 11,
    width: 12,
    fontWeight: '700',
  },
  navDropdownThemeSwatch: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1,
  },
  navDropdownSignOutText: {
    fontSize: 13,
    color: '#ef4444',
  },
  userAvatarBig: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  userAvatarBigPhoto: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#e5e7eb',
    flexShrink: 0,
  },
  userAvatarBigText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
  },
  userAvatarBigAnimal: {
    fontSize: 22,
    lineHeight: 28,
  },
  userMeta: {
    flexShrink: 1,
    flex: 1,
  },
  userMetaNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    minHeight: 21,
  },
  userNameButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    flexShrink: 0,
    maxWidth: 128,
  },
  userMetaName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#111827',
  },
  userNavChevron: {
    fontSize: 14,
    color: '#9ca3af',
    lineHeight: 16,
    fontWeight: '800',
  },
  userMetaStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 2,
    flex: 1,
  },
  onlineDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#22c55e',
    flexShrink: 0,
  },
  onlineDotInactive: {
    backgroundColor: '#d1d5db',
  },
  statusPressable: {
    flex: 1,
    minWidth: 0,
  },
  statusText: {
    fontSize: 11,
    color: '#6b7280',
    fontStyle: 'italic',
  },
  statusPlaceholder: {
    fontSize: 11,
    color: '#d1d5db',
  },
  statusInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 11,
    color: '#6b7280',
    fontStyle: 'italic',
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  workspaceActiveBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 5,
  },
  workspaceActiveTrack: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#eef2ff',
    overflow: 'hidden',
  },
  workspaceActiveFill: {
    height: '100%',
    borderRadius: 2,
    backgroundColor: '#22c55e',
  },
  workspaceActiveText: {
    width: 56,
    fontSize: 10,
    color: '#9ca3af',
    fontWeight: '700',
    textAlign: 'right',
  },
  titleBarCenter: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
    minWidth: 0,
  },
  messageBoard: {
    flex: 1,
    maxWidth: 360,
    minWidth: 180,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  messageBoardItem: {
    flex: 1,
    minWidth: 0,
    height: '100%',
    justifyContent: 'center',
    borderLeftWidth: 4,
    paddingHorizontal: 9,
  },
  messageBoardPresence: {
    borderLeftColor: '#22c55e',
    backgroundColor: '#f0fdf4',
  },
  messageBoardChat: {
    borderLeftColor: '#6366f1',
    backgroundColor: '#eef2ff',
  },
  messageBoardText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#374151',
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    gap: 6,
    width: workspaceInboxColumnWidth,
    flexShrink: 0,
    height: 36,
  },
  searchIcon: {
    fontSize: 15,
    color: '#9ca3af',
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    color: '#111827',
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  searchClearButton: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e5e7eb',
  },
  searchClearText: {
    fontSize: 14,
    lineHeight: 16,
    color: '#6b7280',
    fontWeight: '700',
  },
  searchShortcut: {
    fontSize: 11,
    color: '#c4c9d4',
    fontWeight: '600',
  },
  accountAvatarButton: {
    borderRadius: 22,
    padding: 2,
  },
  avatarBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
  },
  avatarAnimal: {
    fontSize: 18,
    lineHeight: 22,
  },
  kanban: {
    flex: 1,
  },
  kanbanContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 12,
    paddingTop: 14,
    paddingBottom: 24,
    gap: 12,
  },
  kanbanCol: {
    width: 280,
    flexShrink: 0,
    backgroundColor: '#f9fafb',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    overflow: 'hidden',
  },
  kanbanColHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e5e7eb',
    gap: 8,
    backgroundColor: '#fff',
  },
  kanbanStatusDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    flexShrink: 0,
  },
  kanbanColMeta: {
    flex: 1,
    minWidth: 0,
  },
  kanbanColMenuButton: {
    width: 28,
    height: 28,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  kanbanColTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#111827',
  },
  kanbanColDateRange: {
    fontSize: 11,
    color: '#9ca3af',
    marginTop: 1,
  },
  kanbanCountBadge: {
    backgroundColor: '#e5e7eb',
    borderRadius: 10,
    paddingHorizontal: 7,
    paddingVertical: 2,
    minWidth: 22,
    alignItems: 'center',
  },
  kanbanCountText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6b7280',
  },
  kanbanColInput: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e5e7eb',
    gap: 6,
    backgroundColor: '#fff',
  },
  kanbanInputField: {
    flex: 1,
    height: 34,
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 13,
    color: '#111827',
  },
  kanbanAddBtn: {
    width: 34,
    height: 34,
    backgroundColor: '#6366f1',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  kanbanAddBtnText: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '300',
    lineHeight: 26,
  },
  kanbanColBody: {
    flex: 1,
    minHeight: 120,
    maxHeight: 520,
  },
  kanbanAddCol: {
    width: 140,
    height: 76,
    flexShrink: 0,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    marginTop: 2,
  },
  kanbanAddColIcon: {
    fontSize: 22,
    color: '#d1d5db',
    fontWeight: '300',
    lineHeight: 26,
  },
  kanbanAddColText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#9ca3af',
  },
  backlogStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#f9fafb',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e5e7eb',
    minHeight: 44,
    gap: 8,
  },
  backlogLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6b7280',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    flexShrink: 0,
  },
  backlogCountBadge: {
    backgroundColor: '#e5e7eb',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    flexShrink: 0,
  },
  backlogCountText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6b7280',
  },
  backlogItemsScroll: {
    flex: 1,
  },
  backlogItemsContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingRight: 4,
  },
  backlogChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    gap: 4,
    maxWidth: 160,
  },
  backlogChipMilestone: {
    borderColor: '#a78bfa',
    backgroundColor: '#f5f3ff',
  },
  backlogMilestoneIcon: {
    fontSize: 9,
    color: '#7c3aed',
  },
  backlogChipText: {
    fontSize: 13,
    color: '#374151',
    fontWeight: '500',
  },
  backlogInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
  },
  backlogInput: {
    height: 32,
    minWidth: 140,
    maxWidth: 220,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#6366f1',
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 13,
    color: '#111827',
  },
  backlogConfirmBtn: {
    height: 32,
    paddingHorizontal: 12,
    backgroundColor: '#6366f1',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backlogConfirmText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
  backlogCancelText: {
    fontSize: 15,
    color: '#9ca3af',
    lineHeight: 20,
  },
  backlogAddBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  backlogAddBtnText: {
    fontSize: 18,
    color: '#6b7280',
    lineHeight: 22,
    fontWeight: '300',
  },
  milestoneBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#fefce8',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#fde68a',
  },
  milestoneBannerOverdue: {
    backgroundColor: '#fef2f2',
    borderBottomColor: '#fecaca',
  },
  milestoneBannerText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#92400e',
  },
  phasePill: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 2,
  },
  phasePillActive: {
    backgroundColor: '#eef2ff',
    borderColor: '#6366f1',
  },
  phasePillText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
  },
  phasePillTextActive: {
    color: '#4338ca',
  },
  milestoneToggle: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 10,
    alignItems: 'center',
  },
  milestoneToggleActive: {
    backgroundColor: '#fefce8',
    borderColor: '#fde68a',
  },
  milestoneToggleText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6b7280',
  },
  milestoneToggleTextActive: {
    color: '#92400e',
  },
  editModalSectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9ca3af',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  aboutText: {
    fontSize: 13,
    color: '#374151',
    lineHeight: 22,
    marginBottom: 12,
  },
  animalGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  avatarUploadButton: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
    backgroundColor: '#f9fafb',
  },
  avatarUploadButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#374151',
  },
  avatarUploadHint: {
    fontSize: 11,
    color: '#9ca3af',
    marginTop: 2,
  },
  animalCell: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f3f4f6',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  animalCellActive: {
    backgroundColor: '#eef2ff',
    borderColor: '#6366f1',
  },
  animalCellText: {
    fontSize: 26,
    lineHeight: 32,
  },
  projectSwitchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e5e7eb',
    gap: 8,
  },
  projectSwitchLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9ca3af',
    textTransform: 'uppercase',
    width: 48,
  },
  projectSwitchScroll: {
    flex: 1,
    minWidth: 0,
  },
  projectSwitchList: {
    gap: 8,
    paddingRight: 2,
  },
  projectSwitchButton: {
    minHeight: 32,
    maxWidth: 180,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    paddingHorizontal: 8,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  projectSwitchButtonActive: {
    backgroundColor: '#eef2ff',
    borderColor: '#6366f1',
  },
  projectSwitchAvatar: {
    width: 24,
    height: 24,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  projectSwitchAvatarText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
  },
  projectSwitchButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
    flexShrink: 1,
  },
  projectSwitchButtonTextActive: {
    color: '#4338ca',
  },
  projectSwitchAddButton: {
    width: 32,
    minHeight: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  projectSwitchAddButtonText: {
    color: '#6366f1',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 22,
  },
  projectViewModeBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#fff',
  },
  projectViewModeMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
    minWidth: 0,
  },
  projectOwnerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#fecaca',
    backgroundColor: '#fff1f2',
    minWidth: 0,
    flexShrink: 1,
  },
  projectOwnerAvatarRing: {
    padding: 2,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: '#ef4444',
  },
  projectOwnerBadgeText: {
    minWidth: 0,
    flexShrink: 1,
  },
  projectOwnerBadgeName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#991b1b',
    lineHeight: 16,
  },
  projectOwnerAddButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#fecaca',
    backgroundColor: '#fff1f2',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  projectOwnerAddButtonText: {
    fontSize: 18,
    lineHeight: 20,
    fontWeight: '700',
    color: '#dc2626',
  },
  projectMemberAvatarRow: {
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
    flexShrink: 0,
  },
  projectViewModeButton: {
    minHeight: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 6,
    justifyContent: 'center',
  },
  projectViewModeButtonActive: {
    backgroundColor: '#111827',
    borderColor: '#111827',
  },
  projectViewModeButtonText: {
    color: '#374151',
    fontSize: 13,
    fontWeight: '700',
  },
  projectViewModeButtonTextActive: {
    color: '#fff',
  },
  projectHeaderBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 8,
    backgroundColor: '#fff',
  },
  projectHeaderTextWrap: {
    flex: 1,
    minWidth: 0,
    marginRight: 12,
  },
  projectHeaderLabel: {
    fontSize: 11,
    color: '#9ca3af',
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  projectHeaderTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111827',
    marginTop: 2,
  },
  projectHeaderRenameButton: {
    minHeight: 32,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    justifyContent: 'center',
  },
  projectHeaderRenameButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#374151',
  },
  teamLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#f3f4f6',
    gap: 10,
  },
  teamLinkDot: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  teamLinkDotText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
  },
  teamLinkRowText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: '#111827',
  },
  teamLinkMeta: {
    fontSize: 11,
    color: '#9ca3af',
  },
  projectPickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  projectPickerRowActive: {
    backgroundColor: '#eef2ff',
    borderColor: '#c7d2fe',
  },
  projectPickerAvatar: {
    width: 28,
    height: 28,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  projectPickerAvatarText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
  },
  projectPickerEmptyAvatar: {
    width: 28,
    height: 28,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f3f4f6',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    flexShrink: 0,
  },
  projectPickerEmptyAvatarText: {
    color: '#9ca3af',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 20,
  },
  projectPickerRowText: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
  },
  projectPickerRowTextActive: {
    color: '#4338ca',
  },
  colAssigneeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingBottom: 6,
    gap: 6,
  },
  colAssigneeAvatar: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0.55,
  },
  colAssigneeAvatarSelected: {
    opacity: 1,
    borderWidth: 2,
    borderColor: '#fff',
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 3,
  },
  colAssigneeInitial: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  colAssigneeName: {
    fontSize: 11,
    color: '#6366f1',
    fontWeight: '600',
    flexShrink: 1,
  },
  assigneePickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#f3f4f6',
    gap: 10,
  },
  assigneePickerAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  assigneePickerAvatarText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
  },
  assigneePickerName: {
    flex: 1,
    fontSize: 13,
    color: '#111827',
    fontWeight: '500',
  },
  assigneePickerCheck: {
    fontSize: 15,
    color: '#6366f1',
    fontWeight: '700',
    flexShrink: 0,
  },
  orgMemberRowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  orgMemberManageIcon: {
    fontSize: 13,
    color: '#9ca3af',
  },
  projectAccessSection: {
    marginTop: 12,
  },
  manageMemberAction: {
    paddingVertical: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#f3f4f6',
    marginTop: 4,
  },
  manageMemberActionDisabled: {
    opacity: 0.5,
  },
  manageMemberActionText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111827',
  },
  manageMemberActionNote: {
    fontSize: 11,
    color: '#6b7280',
    marginTop: 2,
  },
  projectAccessAddGlyph: {
    fontSize: 20,
    lineHeight: 20,
    fontWeight: '700',
    color: '#6366f1',
    flexShrink: 0,
  },
  manageMemberActionDanger: {
    color: '#dc2626',
  },
  orgMemberList: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    marginBottom: 12,
    overflow: 'hidden',
  },
  orgMemberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#f3f4f6',
  },
  orgMemberEmail: {
    flex: 1,
    fontSize: 13,
    color: '#111827',
    marginRight: 8,
  },
  orgMemberRole: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6b7280',
    textTransform: 'uppercase',
  },
  pickerSectionDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
    gap: 8,
  },
  pickerSectionLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#e5e7eb',
  },
  pickerSectionLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#9ca3af',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  pickerConfirmBtn: {
    backgroundColor: '#6366f1',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 8,
  },
  pickerConfirmText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 13,
  },
  archiveBtnText: {
    fontSize: 13,
    color: '#9ca3af',
    fontWeight: '600',
  },
  columnDeleteText: {
    color: '#dc2626',
  },
  columnDeleteTextDisabled: {
    color: '#d1d5db',
  },
  columnDeleteConfirm: {
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  columnDeleteConfirmText: {
    color: '#991b1b',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  editModalActionsRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  archivedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 2,
    paddingLeft: 62,
    paddingRight: 2,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#f3f4f6',
    gap: 8,
  },
  archivedText: {
    flex: 1,
    fontSize: 11,
    fontWeight: '400',
    color: '#9ca3af',
  },
  archivedDateText: {
    width: 54,
    textAlign: 'right',
    fontSize: 11,
    fontWeight: '400',
    color: '#9ca3af',
  },
  unarchiveBtn: {
    paddingHorizontal: 8,
    paddingVertical: 1,
    borderRadius: 6,
    backgroundColor: '#f3f4f6',
  },
  unarchiveBtnText: {
    fontSize: 11,
    fontWeight: '400',
    color: '#9ca3af',
  },
  assignedToMeRowOuter: {
    flexDirection: 'column',
    zIndex: 1,
  },
  assignedToMeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 24,
    paddingVertical: 2,
    paddingHorizontal: 2,
    gap: 8,
    position: 'relative',
  },
  assignedToMeRowHovered: {
    zIndex: 50,
  },
  assignedToMeSeparator: {
    height: 1,
    backgroundColor: '#e5e7eb',
  },
  incomingAcceptIcon: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#c7d2fe',
    backgroundColor: '#eef2ff',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  incomingAcceptTooltip: {
    position: 'absolute',
    top: 32,
    left: 0,
    zIndex: 10,
    borderRadius: 6,
    backgroundColor: '#111827',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  incomingAcceptTooltipText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  inboxSentStatePill: {
    width: 18,
    height: 18,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f3f4f6',
    borderWidth: 1,
    borderColor: '#d1d5db',
    flexShrink: 0,
  },
  inboxSentStatePillAccepted: {
    backgroundColor: '#ecfdf5',
    borderColor: '#86efac',
  },
  inboxSentStateText: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 14,
  },
  inboxSentStateTextAccepted: {
    color: '#16a34a',
  },
  assignedToMeText: {
    flex: 1,
    fontSize: 15,
    color: '#374151',
  },
  assignedToMeContext: {
    fontSize: 11,
    color: '#9ca3af',
    flexShrink: 1,
  },
  assignedToMeDue: {
    fontSize: 11,
    color: '#9ca3af',
    flexShrink: 0,
  },
  assignedToMeDueOverdue: {
    color: '#dc2626',
    fontWeight: '600',
  },
  assignedToMeTooltip: {
    position: 'absolute',
    top: 34,
    left: 50,
    right: 14,
    zIndex: 80,
    borderRadius: 6,
    backgroundColor: '#111827',
    paddingHorizontal: 10,
    paddingVertical: 7,
    shadowColor: '#000',
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  assignedToMeTooltipText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  assignedToMeTooltipNote: {
    color: '#d1d5db',
    fontSize: 11,
    lineHeight: 15,
    marginTop: 4,
  },
  assignedToMePriority: {
    width: 20,
    height: 20,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    marginTop: 2,
  },
  assignedToMePriorityText: {
    fontSize: 11,
    fontWeight: '700',
  },
  priorityPickerRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 2,
  },
  priorityPickerBtn: {
    flex: 1,
    height: 34,
    justifyContent: 'center',
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  priorityPickerLabel: {
    fontSize: 11,
    fontWeight: '600',
  },

  // ── Resources view ────────────────────────────────────────────────
  resourcesView: {
    flex: 1,
  },
  resourcesContent: {
    padding: 24,
    maxWidth: 860,
    alignSelf: 'center',
    width: '100%',
  },
  resourcesHeader: {
    marginBottom: 24,
  },
  resourcesTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  resourcesSubtitle: {
    fontSize: 13,
    color: '#6b7280',
  },
  resourcesSectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9ca3af',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginTop: 16,
    marginBottom: 8,
  },
  resourceCard: {
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 16,
    marginBottom: 10,
  },
  resourceCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  resourceCardName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
  },
  resourceCardMeta: {
    fontSize: 12,
    color: '#9ca3af',
    textTransform: 'capitalize',
  },
  resourceStats: {
    flexDirection: 'row',
    gap: 12,
  },
  resourceStat: {
    minWidth: 64,
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  resourceStatDanger: {
    backgroundColor: '#fef2f2',
  },
  resourceStatUrgent: {
    backgroundColor: '#fef2f2',
  },
  resourceStatValue: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
  },
  resourceStatValueDanger: {
    color: '#dc2626',
  },
  resourceStatValueUrgent: {
    color: '#ef4444',
  },
  resourceStatLabel: {
    fontSize: 11,
    color: '#6b7280',
    marginTop: 2,
  },
  resourcesEmpty: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  resourcesEmptyText: {
    fontSize: 14,
    color: '#9ca3af',
    textAlign: 'center',
  },

  // ── Dashboard view ────────────────────────────────────────────────
  dashboardView: {
    flex: 1,
  },
  dashboardContent: {
    padding: 24,
    maxWidth: 860,
    alignSelf: 'center',
    width: '100%',
  },
  dashboardHeader: {
    marginBottom: 24,
  },
  dashboardTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  dashboardSubtitle: {
    fontSize: 13,
    color: '#6b7280',
  },
  dashboardStatGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 24,
  },
  dashboardStatCard: {
    flexBasis: '30%',
    flexGrow: 1,
    borderRadius: 10,
    padding: 16,
    alignItems: 'center',
    minWidth: 100,
  },
  dashboardStatValue: {
    fontSize: 32,
    fontWeight: '700',
    marginBottom: 4,
  },
  dashboardStatLabel: {
    fontSize: 12,
    color: '#6b7280',
    fontWeight: '600',
  },
  dashboardSectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#374151',
    letterSpacing: 0.3,
    marginBottom: 10,
    marginTop: 8,
  },
  dashboardMemberGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 20,
  },
  dashboardMemberCard: {
    flexBasis: '30%',
    flexGrow: 1,
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    minWidth: 120,
  },
  dashboardMemberName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  dashboardMemberStats: {
    fontSize: 12,
    color: '#6b7280',
  },
  dashboardTodoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 9,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e5e7eb',
    gap: 10,
  },
  dashboardTodoPriority: {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
  },
  dashboardTodoText: {
    flex: 1,
    fontSize: 14,
    color: '#111827',
  },
  dashboardTodoDue: {
    fontSize: 12,
    color: '#dc2626',
  },
  dashboardMoreText: {
    fontSize: 12,
    color: '#9ca3af',
    paddingVertical: 8,
  },
});
